onEvent('recipes', event => {
    // event.remove({id: 'create:crafting/materials/rose_quartz'})
    // event.replaceInput({id:/.*thermal\:fire_charge.*/}, "minecraft:fire_charge", "forbidden_arcanus:smelter_prism")
    // event.remove({mod: "thermal", id: /.*dust_[0-9]/})
    event.remove({output: 'createindustry:lpg_engine_back'})
    event.remove({output: 'waterstrainer:strainer_base'})
    event.remove({output: 'createindustry:lpg_engine'})
    event.remove({output: 'createdieselgenerators:basin_lid'})
    event.remove({id: "createdieselgenerators:mechanical_crafting/diesel_engine"})
    event.remove({output: 'create:cogwheel'})
    event.remove({output: 'create:large_cogwheel'})
    event.remove({output: /^createdieselgenerators:pumpjack.*/ })
    event.remove({output: 'createdieselgenerators:distillation_controller'})
    event.remove({output: 'createdieselgenerators:oil_scanner'})
    event.remove({output: 'createdieselgenerators:ethanol_bucket'})
    //event.remove({type: 'createdieselgenerators:fermenting', output: 'createdieselgenerators:ethanol'})
    event.remove({type: 'createdieselgenerators:distillation'})
    // event.remove({output: /waystones\:.*sharestone/})
})   